### ISSUE TITLE
Redis client support

### ISSUE THREAD

**Issue by ActionJ4ckson** [awslabs/elasticache-cluster-config-net#7]
This is a query, not an issue. This is embarrassing but I am not able to figure out how use client for Redis (not memcached) using Elasticache? My requirement is just to connect to the Redis cache and insert and fetch items. I don't want to use StackExchange.Redis solution, as it is causing a random connection errors at run time. 
Thanks in advance.

**Comment by normj** [comment]
Sorry but this repository is for tooling to help the Memcached version of ElastiCache. I don't have the experience with Redis to answer this question.
